services:
  db:
    image: postgres:15
    container_name: po_db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: po_db
    ports:
      - "5432:5432"
    volumes:
      - ./init-postgres.sql:/docker-entrypoint-initdb.d/init-postgres.sql

  backend:
    build: ./backend_python
    container_name: po_backend
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://admin:password@db/po_db
      - GEMINI_API_KEY=${GEMINI_API_KEY}
    depends_on:
      - db
